<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>kfsgm</groupId>
    <artifactId>KfsGm1</artifactId>
    <version>1</version>
    <packaging>war</packaging>
    <name>KfsGm1</name>
    <description>Gm1</description>
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <teavm.version>0.12.3</teavm.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.teavm</groupId>
            <artifactId>teavm-classlib</artifactId>
            <version>${teavm.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.teavm</groupId>
            <artifactId>teavm-jso-apis</artifactId>
            <version>${teavm.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>

            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.4.0</version>
                <configuration>
                    <webResources>
                        <resource>
                            <directory>${project.build.directory}/generated/js</directory>
                        </resource>
                    </webResources>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.teavm</groupId>
                <artifactId>teavm-maven-plugin</artifactId>
                <version>${teavm.version}</version>
                <executions>
                    <execution>
                        <id>web-client</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <targetDirectory>${project.build.directory}/generated/js</targetDirectory>
                            <mainClass>kfs.gm.GmMain</mainClass>
                            <minifying>true</minifying>
                            <debugInformationGenerated>false</debugInformationGenerated>
                            <sourceMapsGenerated>false</sourceMapsGenerated>
                            <optimizationLevel>ADVANCED</optimizationLevel>
                        </configuration>
                    </execution>
                </executions>
            </plugin>


        </plugins>
    </build>
</project>
